USE ZbussDb_Dev;
GO
DROP PROCEDURE IF EXISTS ZB_SP_API_INS_BUS;
GO
CREATE PROCEDURE ZB_SP_API_INS_BUS
	@PARAM_CH_PLACA CHAR(7),
	@PARAM_VC_CATEGORIA VARCHAR(50),
	@PARAM_DE_PESO_NETO DECIMAL,
	@PARAM_IN_ASIENTOS INT
AS
BEGIN
	DECLARE @Contador INT
    DECLARE @Limite INT
	DECLARE @IdBus INT

	SET @Contador = 1
    SET @Limite = @PARAM_IN_ASIENTOS	
	
	INSERT INTO ZB_TA_BUS(CH_PLACA,VC_CATEGORIA,DE_PESO_NETO,CH_SITUACION_REGISTRO)
	SELECT @PARAM_CH_PLACA, @PARAM_VC_CATEGORIA, @PARAM_DE_PESO_NETO, 'A'
	WHERE NOT EXISTS(
		SELECT * FROM ZB_TA_BUS B
		WHERE B.CH_PLACA = @PARAM_CH_PLACA
		AND B.CH_SITUACION_REGISTRO = 'A')

	SET @IdBus = (SELECT MAX(IN_ID_BUS) FROM ZB_TA_BUS)

	WHILE @Contador <= @Limite
	BEGIN
		INSERT INTO ZB_TA_ASIENTO(IN_ID_BUS, CH_NUMERO_ASIENTO,VC_INCLINACION,CH_SITUACION_REGISTRO)
		SELECT @IdBus, FORMAT(@Contador, '00'),'°180','A'
		SET @Contador = @Contador + 1
	END
END;