USE ZbussDb_Dev;
GO
DROP PROCEDURE IF EXISTS ZB_SP_API_ASIENTOS_SEL;
GO
CREATE PROCEDURE ZB_SP_API_ASIENTOS_SEL
	@PARAM_IN_ID_BUS INT
AS
BEGIN
	SELECT 
		A.IN_ID_ASIENTO,
		A.IN_ID_BUS,
		A.CH_NUMERO_ASIENTO,
		A.VC_INCLINACION,
		A.VC_TIPO_BLOQUE,
		A.IN_PISO
	FROM ZB_TA_ASIENTO A
	WHERE A.IN_ID_BUS = @PARAM_IN_ID_BUS
	AND A.CH_SITUACION_REGISTRO = 'A'
	ORDER BY A.CH_NUMERO_ASIENTO ASC;
END;