USE ZbussDb_Dev;
GO
DROP PROCEDURE IF EXISTS ZB_SP_API_DEL_USUARIO;
GO
CREATE PROCEDURE ZB_SP_API_DEL_USUARIO
	@PARAM_IN_ID_USUARIO INT
AS
BEGIN
	UPDATE ZB_TA_USUARIO SET
		CH_SITUACION_REGISTRO = 'E'
	WHERE IN_ID_USUARIO = @PARAM_IN_ID_USUARIO;
END;