USE ZbussDb_Dev;
GO
DROP PROCEDURE IF EXISTS ZB_SP_API_BUSES_SEL;
GO
CREATE PROCEDURE ZB_SP_API_BUSES_SEL
AS
BEGIN
	SELECT 
		IN_ID_BUS,
		CH_PLACA,
		VC_CATEGORIA,
		DE_PESO_NETO,
		CH_SITUACION_REGISTRO
	FROM ZB_TA_BUS WHERE CH_SITUACION_REGISTRO = 'A';
END;