USE ZbussDb_Dev;
GO
DROP PROCEDURE IF EXISTS ZB_SP_API_VALIDAR_CREDENCIALES_SEL;
GO
CREATE PROCEDURE ZB_SP_API_VALIDAR_CREDENCIALES_SEL
	@PARAM_VC_CORREO VARCHAR(50),
	@PARAM_VC_CONTRASENA VARCHAR(100)
AS
BEGIN
	DECLARE @CH_INDICADOR CHAR(1);
	DECLARE @VC_MENSAJE VARCHAR(80);

	IF EXISTS (SELECT 1 FROM ZB_TA_USUARIO WHERE VC_CORREO = @PARAM_VC_CORREO AND VC_CONTRASENA = @PARAM_VC_CONTRASENA)
	BEGIN
    -- Código a ejecutar si existe al menos un registro
		SET @CH_INDICADOR = '1';
		SET @VC_MENSAJE = 'Validado Correctamente, bienvenido!';
	END
	ELSE
	BEGIN
		SET @CH_INDICADOR = '0';
		SET @VC_MENSAJE = 'Correo y/o contraseña incorrecto';
	END

	SELECT @CH_INDICADOR AS 'CH_INDICADOR', @VC_MENSAJE AS 'VC_MENSAJE';
	-- Devolver datos del usuario
	SELECT VC_NOMBRES, VC_APELLIDOS, VC_CORREO, VC_CONTRASENA FROM ZB_TA_USUARIO WHERE VC_CORREO = @PARAM_VC_CORREO AND VC_CONTRASENA = @PARAM_VC_CONTRASENA;
END;