USE ZbussDb_Dev;
GO
DROP PROCEDURE IF EXISTS ZB_SP_API_UPD_USUARIO;
GO
CREATE PROCEDURE ZB_SP_API_UPD_USUARIO
	@PARAM_IN_ID_USUARIO INT,
	@PARAM_VC_NOMBRES VARCHAR(50),
	@PARAM_VC_APELLIDOS VARCHAR(80),
	@PARAM_VC_CORREO VARCHAR(50),
	@PARAM_VC_CONTRASENA VARCHAR(100)
AS
BEGIN
	UPDATE ZB_TA_USUARIO SET
		VC_NOMBRES = @PARAM_VC_NOMBRES,
		VC_APELLIDOS = @PARAM_VC_APELLIDOS,
		VC_CORREO = @PARAM_VC_CORREO,
		VC_CONTRASENA = @PARAM_VC_CONTRASENA
	WHERE IN_ID_USUARIO = @PARAM_IN_ID_USUARIO;
END;