USE ZbussDb_Dev;
GO
DROP PROCEDURE IF EXISTS ZB_SP_API_DEL_BUS;
GO
CREATE PROCEDURE ZB_SP_API_DEL_BUS
	@PARAM_IN_ID_BUS INT
AS
BEGIN
	UPDATE ZB_TA_BUS SET
		CH_SITUACION_REGISTRO = 'E'
	WHERE IN_ID_BUS = @PARAM_IN_ID_BUS;

	UPDATE ZB_TA_ASIENTO SET
		CH_SITUACION_REGISTRO = 'E'
	WHERE IN_ID_BUS = @PARAM_IN_ID_BUS;
END;