USE ZbussDb_Dev;
GO
DROP PROCEDURE IF EXISTS ZB_SP_API_INS_BUS;
GO
CREATE PROCEDURE ZB_SP_API_INS_BUS
	@PARAM_CH_PLACA CHAR(7),
	@PARAM_VC_CATEGORIA VARCHAR(50),
	@PARAM_DE_PESO_NETO DECIMAL,
	@PARAM_IN_PISOS INT,
	@PARAM_IN_ASIENTOS_1 INT,
	@PARAM_IN_ASIENTOS_2 INT
AS
BEGIN
	DECLARE @Contador INT
	DECLARE @NumeroAsiento INT
	DECLARE @IdBus INT

	SET @Contador = 1
	SET @NumeroAsiento = 1
	
	INSERT INTO ZB_TA_BUS(CH_PLACA,VC_CATEGORIA,DE_PESO_NETO,IN_NUMERO_PISOS,CH_SITUACION_REGISTRO)
	SELECT @PARAM_CH_PLACA, @PARAM_VC_CATEGORIA, @PARAM_DE_PESO_NETO, @PARAM_IN_PISOS, 'A'
	WHERE NOT EXISTS(
		SELECT * FROM ZB_TA_BUS B
		WHERE B.CH_PLACA = @PARAM_CH_PLACA
		AND B.CH_SITUACION_REGISTRO = 'A')

	SET @IdBus = (SELECT MAX(IN_ID_BUS) FROM ZB_TA_BUS)

	-- Insertando los asientos del bus
	IF @PARAM_IN_ASIENTOS_1 > 0
	BEGIN
		WHILE @Contador <= @PARAM_IN_ASIENTOS_1
		BEGIN
			INSERT INTO ZB_TA_ASIENTO(IN_ID_BUS, CH_NUMERO_ASIENTO,VC_INCLINACION,VC_TIPO_BLOQUE,IN_PISO,CH_SITUACION_REGISTRO)
			SELECT @IdBus, FORMAT(@NumeroAsiento, '00'),'°180','01',1,'A'
			SET @NumeroAsiento = @NumeroAsiento + 1
			SET @Contador = @Contador + 1
		END
	END
	IF @PARAM_IN_ASIENTOS_2 > 0
	BEGIN
		SET @Contador = 1

		WHILE @Contador <= @PARAM_IN_ASIENTOS_2
		BEGIN
			INSERT INTO ZB_TA_ASIENTO(IN_ID_BUS, CH_NUMERO_ASIENTO,VC_INCLINACION,VC_TIPO_BLOQUE,IN_PISO,CH_SITUACION_REGISTRO)
			SELECT @IdBus, FORMAT(@NumeroAsiento, '00'),'°180','01',2,'A'
			SET @NumeroAsiento = @NumeroAsiento + 1
			SET @Contador = @Contador + 1
		END
	END
END;