USE ZbussDb_Dev;
GO
DROP PROCEDURE IF EXISTS ZB_SP_API_GENERAL_SEL;
GO
CREATE PROCEDURE ZB_SP_API_GENERAL_SEL
	@PARAM_VC_NOMBRE_TABLA VARCHAR(100),
	@PARAM_VC_COLUMNA VARCHAR(50)
AS
BEGIN
	SELECT 
		G.IN_ID_GENERAL,
		G.VC_NOMBRE_TABLA,
		G.VC_COLUMNA,
		G.VC_VALOR_COLUMNA,
		G.VC_VALOR_COLUMNA_2,
		G.CH_SITUACION_REGISTRO
	FROM ZB_TA_GENERAL G
	WHERE G.VC_NOMBRE_TABLA = @PARAM_VC_NOMBRE_TABLA
	AND G.VC_COLUMNA = @PARAM_VC_COLUMNA
	AND G.CH_SITUACION_REGISTRO = 'A'
	ORDER BY G.VC_VALOR_COLUMNA ASC;
END;