USE ZbussDb_Dev;
GO
DROP PROCEDURE IF EXISTS ZB_SP_API_INS_USUARIO;
GO
CREATE PROCEDURE ZB_SP_API_INS_USUARIO
	@PARAM_VC_NOMBRES VARCHAR(50),
	@PARAM_VC_APELLIDOS VARCHAR(80),
	@PARAM_VC_CORREO VARCHAR(50),
	@PARAM_VC_CONTRASENA VARCHAR(100)
AS
BEGIN
	INSERT INTO ZB_TA_USUARIO (VC_NOMBRES, VC_APELLIDOS, VC_CORREO, VC_CONTRASENA, CH_SITUACION_REGISTRO)
	SELECT @PARAM_VC_NOMBRES, @PARAM_VC_APELLIDOS, @PARAM_VC_CORREO, @PARAM_VC_CONTRASENA, 'A'
	WHERE NOT EXISTS(
		SELECT * FROM ZB_TA_USUARIO U
		WHERE U.VC_CORREO = @PARAM_VC_CORREO
		AND U.CH_SITUACION_REGISTRO = 'A');
END;