DROP TABLE IF EXISTS ZB_TA_USUARIO;
CREATE TABLE ZB_TA_USUARIO
(
    IN_ID_USUARIO INT IDENTITY(1,1) PRIMARY KEY,
    VC_NOMBRES VARCHAR(50),
    VC_APELLIDOS VARCHAR(80),
    VC_CORREO VARCHAR(50),
	VC_CONTRASENA VARCHAR(100),
	CH_SITUACION_REGISTRO CHAR(1)
);