USE ZbussDb_Dev;
GO

INSERT INTO ZB_TA_GENERAL (VC_NOMBRE_TABLA,VC_COLUMNA,VC_VALOR_COLUMNA,VC_VALOR_COLUMNA_2,CH_SITUACION_REGISTRO)
VALUES 
('TIPOS_BLOQUES_AUTOBUS','OPCIONES','Asiento','01','A'),
('TIPOS_BLOQUES_AUTOBUS','OPCIONES','Baño','02','A'),
('TIPOS_BLOQUES_AUTOBUS','OPCIONES','Conductor','03','A'),
('TIPOS_BLOQUES_AUTOBUS','OPCIONES','Vacío','04','A'),
('TIPOS_BLOQUES_AUTOBUS','OPCIONES','Escalera','05','A')